#! /bin/sh
A=$1
B=$2
C=$3
case "$2" in
+)
	echo "`expr $1 + $3`"
       ;;
-)
	echo "`expr $1 - $3`"
	;;
x)
	echo "`expr $1 * $3`"
	;;
/)
	echo "`expr $1 / $3`"
	;;
%)
	echo "`expr $1 % $3`"
	;;
*)
	echo "error"
esac
